# ================================================
# Configuration SonarQube pour le Frontend Angular
# ================================================

# Identifiant unique du projet dans SonarQube
sonar.projectKey=JOCL-Frontend
sonar.projectName=JOCL Frontend Angular

# Version
sonar.projectVersion=1.0

# Dossier du code source TypeScript
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**

# Type de langage
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
